- name: create file inside the shellmodule-pao folder
  file: 
    state: touch
    path: "~/shellmodule-pao/{{ item }}"
  with_items:
    - samplefile1
    - samplefile2
    - samplefile3

- name: create file inside the filemodule-pao folder
  file: 
    state: touch
    path: "~/filemodule-pao/{{ item.filename }}_{{ item.envtype }}"
  with_items:
    - { filename: 'file1', envtype: 'CI' }
    - { filename: 'file2', envtype: 'DEV' }
    - { filename: 'file3', envtype: 'TEST' }